# Generated by Django 2.0 on 2018-08-17 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeldingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='', help_text='图片url', verbose_name='图片url')),
                ('predict_label', models.CharField(blank=True, max_length=50, null=True, verbose_name='预测结果')),
                ('real_label', models.CharField(blank=True, max_length=50, null=True, verbose_name='真实结果')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '焊接图片',
                'verbose_name_plural': '焊接图片',
                'db_table': 'welding_image',
            },
        ),
    ]
