# Generated by Django 2.0 on 2018-09-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo_dl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weldingimage',
            name='real_label',
        ),
        migrations.AddField(
            model_name='weldingimage',
            name='has_welding',
            field=models.IntegerField(blank=True, null=True, verbose_name='是否有焊缝'),
        ),
        migrations.AlterField(
            model_name='weldingimage',
            name='predict_label',
            field=models.TextField(blank=True, null=True, verbose_name='预测结果'),
        ),
    ]
